spring:
  minio:
    url:  http://10.254.0.100:9000
    bucket: ${MINIO_BUCKET}
    access-key: ${MINIO_ROOT_USER}
    secret-key: ${MINIO_ROOT_PASSWORD}
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB
  jpa:
    database-platform: org.hibernate.dialect.MySQL55Dialect
  datasource:
    url: jdbc:mysql://${MYSQL_URL}:${MYSQL_PORT}/${MYSQL_DATABASE}?createDatabaseIfNotExist=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
  profiles:
    active: dev
app:
  security:
    secret: ${BCRYPT_SECRET:default}
    access-cookie-name: accessToken
    refresh-cookie-name: refreshToken
    access-token-expiration-time-min: 15
    refresh-token-expiration-time-day: 1
    path: /
    access-cookie-duration-sec: 900
    refresh-cookie-duration-sec: 86400
server:
  servlet:
    context-path: /api/v1
